#Configure a detector

/OpNovice/detector/dimensions 6 6 6 cm
/OpNovice/detector/reflectivity 0.02

#First surface, xy +z
/OpNovice/detector/surface1/PhotoDetectorDimensions 4.8 4.8 0 cm
/OpNovice/detector/surface1/PhotoDetectorQE 0.3
/OpNovice/detector/surface1/PhotoDetectorReflectivity 0.1
/OpNovice/detector/surface1/CouplingThickness 0.2 mm
/OpNovice/detector/surface1/CouplingN 1.5

/OpNovice/detector/surface1/NpixelsX 16
/OpNovice/detector/surface1/NpixelsY 16
/OpNovice/digitizer/detector1/TimeResolution 100 ps

#Third surface, xy -z
/OpNovice/detector/surface3/PhotoDetectorDimensions 4.8 4.8 0 cm
/OpNovice/detector/surface3/PhotoDetectorQE 0.3
/OpNovice/detector/surface3/PhotoDetectorReflectivity 0.1
/OpNovice/detector/surface3/CouplingThickness 0.2 mm
/OpNovice/detector/surface3/CouplingN 1.5

/OpNovice/detector/surface3/NpixelsX 16
/OpNovice/detector/surface3/NpixelsY 16
/OpNovice/digitizer/detector3/TimeResolution 100 ps



#Second surface, yz +x
/OpNovice/detector/surface2/PhotoDetectorDimensions 4.8 4.8 0 cm
#/OpNovice/detector/surface2/PhotoDetectorDimensions 0 0 0 cm
/OpNovice/detector/surface2/PhotoDetectorQE 0.3
/OpNovice/detector/surface2/PhotoDetectorReflectivity 0.1
/OpNovice/detector/surface2/CouplingThickness 0.2 mm
/OpNovice/detector/surface2/CouplingN 1.5

/OpNovice/detector/surface2/NpixelsX 16
/OpNovice/detector/surface2/NpixelsY 16
/OpNovice/digitizer/detector2/TimeResolution 100 ps



#Fourth surface, yz -x
/OpNovice/detector/surface4/PhotoDetectorDimensions 4.8 4.8 0 cm
#/OpNovice/detector/surface4/PhotoDetectorDimensions 0 0 0 cm
/OpNovice/detector/surface4/PhotoDetectorQE 0.3
/OpNovice/detector/surface4/PhotoDetectorReflectivity 0.1
/OpNovice/detector/surface4/CouplingThickness 0.2 mm
/OpNovice/detector/surface4/CouplingN 1.5

/OpNovice/detector/surface4/NpixelsX 16
/OpNovice/detector/surface4/NpixelsY 16
/OpNovice/digitizer/detector4/TimeResolution 100 ps


#Fifth surface, xz +y
#/OpNovice/detector/surface5/PhotoDetectorDimensions 4.8 4.8 0 cm
/OpNovice/detector/surface5/PhotoDetectorDimensions 0 0 0 cm
/OpNovice/detector/surface5/PhotoDetectorQE 0.3
/OpNovice/detector/surface5/PhotoDetectorReflectivity 0.1
/OpNovice/detector/surface5/CouplingThickness 0.2 mm
/OpNovice/detector/surface5/CouplingN 1.5

/OpNovice/detector/surface5/NpixelsX 16
/OpNovice/detector/surface5/NpixelsY 16
/OpNovice/digitizer/detector5/TimeResolution 100 ps


#Sixth surface, xz -y
#/OpNovice/detector/surface6/PhotoDetectorDimensions 4.8 4.8 0 cm
/OpNovice/detector/surface6/PhotoDetectorDimensions 0 0 0 cm
/OpNovice/detector/surface6/PhotoDetectorQE 0.3
/OpNovice/detector/surface6/PhotoDetectorReflectivity 0.1
/OpNovice/detector/surface6/CouplingThickness 0.2 mm
/OpNovice/detector/surface6/CouplingN 1.5

/OpNovice/detector/surface6/NpixelsX 16
/OpNovice/detector/surface6/NpixelsY 16
/OpNovice/digitizer/detector6/TimeResolution 100 ps
